# Generated by Django 5.2.8 on 2025-11-29 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkingprofile',
            old_name='about',
            new_name='goal',
        ),
        migrations.RenameField(
            model_name='networkingprofile',
            old_name='last_filled_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='networkingprofile',
            name='event',
        ),
        migrations.RemoveField(
            model_name='networkingprofile',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='networkingprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='networkingprofile',
            name='looking_for',
        ),
        migrations.RemoveField(
            model_name='networkingprofile',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='networkingprofile',
            name='age',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkingprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkingprofile',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkingprofile',
            name='stack',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkingprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networking_profile', to='core.telegramuser'),
        ),
        migrations.DeleteModel(
            name='NetworkingEncounter',
        ),
    ]
